In [1]:
pip install gymnasium

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install "gymnasium["toy-text"]"

Note: you may need to restart the kernel to use updated packages.


In [3]:
import gymnasium as gym 
import numpy as np
import random

In [4]:
#sample env
env = gym.make("CliffWalking-v1")


In [5]:
print(env.observation_space.n)
print(env.action_space.n)
starting_state, _ = env.reset()
print(starting_state)


48
4
36


In [6]:
gamma = 0.99
alpha = 0.5
epsilon = 0.1
episodes = 500

In [7]:
# Qtable that will store Q-value
Q = np.zeros((48,4))
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# we use e- greedy as our policy to update Q value by actions 
#we know esilon greedy mai we chose random action & best known action and since e = 0.1  yaani random action prob = 10% and best action ki 80 %
def epsilon_greedy(state):
    if random.random() < epsilon:
        return env.action_space.sample()  # explore
    else:
        return np.argmax(Q[state]) # exploit  , argmax bcz argmax returns the index of the higest value action eg - Q[state] = [2.5, 9.8, 1.1, 0.4] argmax returns 1 
    
